import { useRef } from 'react';
import { motion, useMotionValue, useSpring, useTransform, useScroll } from 'framer-motion';

/* ════════════════════════════════════════════════════════════════
   Media — presents the BACKGROUND-REMOVED police renders (transparent
   PNGs in /public/cut, generated by scripts/cutout.cjs) as live 3D
   objects: cursor-tilt, idle float, scroll parallax, glow bloom. No
   white box, no blend hacks — they sit on light OR dark.
   ════════════════════════════════════════════════════════════════ */

export const IMG = {
  officer: '/cut/officer.png',
  drone: '/cut/drone.png',
  suv: '/cut/suv.png',
  car: '/cut/car.png',
  camera: '/cut/camera.png',
  watch: '/cut/watch.png',
  badge: '/cut/badge.png',
  map: '/cut/map.png',
};

export function FloatImage({ src, alt, glow = 'var(--azure)', tilt = 12, parallax = 40, floatY = 14, lazy = false }: { src: string; alt: string; glow?: string; tilt?: number; parallax?: number; floatY?: number; lazy?: boolean }) {
  const ref = useRef<HTMLDivElement>(null);
  const mx = useMotionValue(0), my = useMotionValue(0);
  const sx = useSpring(mx, { stiffness: 120, damping: 16 });
  const sy = useSpring(my, { stiffness: 120, damping: 16 });
  const rotateX = useTransform(sy, [-0.5, 0.5], [`${tilt}deg`, `-${tilt}deg`]);
  const rotateY = useTransform(sx, [-0.5, 0.5], [`-${tilt}deg`, `${tilt}deg`]);
  const { scrollYProgress } = useScroll({ target: ref, offset: ['start end', 'end start'] });
  const y = useTransform(scrollYProgress, [0, 1], [parallax, -parallax]);
  const move = (e: React.MouseEvent) => { const el = ref.current; if (!el) return; const r = el.getBoundingClientRect(); mx.set((e.clientX - r.left) / r.width - 0.5); my.set((e.clientY - r.top) / r.height - 0.5); };

  return (
    <motion.div ref={ref} onMouseMove={move} onMouseLeave={() => { mx.set(0); my.set(0); }} style={{ y, position: 'relative', width: '100%', height: '100%', perspective: 1200, display: 'grid', placeItems: 'center' }}>
      <motion.div aria-hidden animate={{ scale: [1, 1.08, 1], opacity: [0.5, 0.8, 0.5] }} transition={{ duration: 6, repeat: Infinity, ease: 'easeInOut' }}
        style={{ position: 'absolute', width: '72%', aspectRatio: '1', borderRadius: '50%', background: `radial-gradient(circle, ${glow}, transparent 64%)`, filter: 'blur(46px)', opacity: 0.6, zIndex: 0 }} />
      <motion.div style={{ rotateX, rotateY, transformStyle: 'preserve-3d', width: '100%', height: '100%', display: 'grid', placeItems: 'center', position: 'relative', zIndex: 1 }}>
        <motion.img src={src} alt={alt} draggable={false} loading={lazy ? 'lazy' : 'eager'} decoding="async"
          animate={{ y: [0, -floatY, 0] }} transition={{ duration: 7, repeat: Infinity, ease: 'easeInOut' }}
          style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain', filter: 'drop-shadow(0 36px 46px rgba(18,26,70,0.30))', transform: 'translateZ(40px)' }} />
      </motion.div>
    </motion.div>
  );
}

/* CardImage — transparent render sized for a card tile (no float, light glow). */
export function CardImage({ src, glow = 'var(--azure)' }: { src: string; glow?: string }) {
  return (
    <div style={{ width: 64, height: 56, flexShrink: 0, position: 'relative', display: 'grid', placeItems: 'center' }}>
      <div aria-hidden style={{ position: 'absolute', inset: 0, borderRadius: 14, background: `radial-gradient(circle at 50% 55%, ${glow}, transparent 70%)`, opacity: 0.22 }} />
      <img src={src} alt="" draggable={false} loading="lazy" decoding="async" style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain', position: 'relative', zIndex: 1, filter: 'drop-shadow(0 6px 10px rgba(18,26,70,0.22))' }} />
    </div>
  );
}

/* MarqueeText — big kinetic outline headline scrolling horizontally. */
export function MarqueeText({ words }: { words: string[] }) {
  const run = [...words, ...words, ...words];
  return (
    <div className="ticker-mask" style={{ overflow: 'hidden', padding: '6px 0' }}>
      <div className="ticker-track" style={{ animationDuration: '42s' }}>
        {run.map((w, i) => (
          <span key={i} style={{ display: 'inline-flex', alignItems: 'center', gap: 30, padding: '0 30px', fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: 'clamp(34px,6.5vw,82px)', letterSpacing: '-0.03em', whiteSpace: 'nowrap', color: 'transparent', WebkitTextStroke: '1.4px rgba(79,70,229,0.30)' }}>
            {w}<span style={{ WebkitTextStroke: '0', color: 'var(--amber)', fontSize: '0.42em' }}>◆</span>
          </span>
        ))}
      </div>
    </div>
  );
}

/* Parallax — translate any block on scroll (depth layering). */
export function Parallax({ children, amount = 80, className = '', style }: { children: React.ReactNode; amount?: number; className?: string; style?: React.CSSProperties }) {
  const ref = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: ref, offset: ['start end', 'end start'] });
  const y = useTransform(scrollYProgress, [0, 1], [amount, -amount]);
  return <motion.div ref={ref} className={className} style={{ y, ...style }}>{children}</motion.div>;
}
